### ISSUE TITLE
java.lang.NoSuchMethodError: net.minecraft.world.WorldServer.notify(III)V

### ISSUE THREAD

**Issue by Himmelt** [Himmelt/Quorra#1]
```java
[19:52:57 INFO]: Himmelt issued server command: //set 1
[19:52:58 WARN]: WorldEdit: Failed to do NMS safe block set
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:1362) [%5B创世神%5DWorldEdit.jar:?]
        at com.sk89q.worldedit.EditSession.rawSetBlock(EditSession.java:233) [%5B创世神%5DWorldEdit.jar:?]
        at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:693) [%5B创世神%5DWorldEdit.jar:?]
        at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1481) [%5B创世神%5DWorldEdit.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [%5B创世神%5DWorldEdit.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52) [%5B创世神%5DWorldEdit.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.UNOFFICIAL]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.UNOFFICIAL]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.WorldServer.notify(III)V
        at com.sk89q.worldedit.bukkit.DefaultNmsBlock.setSafely(DefaultNmsBlock.java:234) ~[?:?]
        ... 23 more
```

**Comment by Himmelt** [comment]
改 worldedit 不太现实，那就只能添加方法了。
